### ISSUE TITLE
Update for the renameing of packages in JavaEE

### ISSUE THREAD

**Issue by jpschewe** [sargue/java-time-jsptags#10]
The JavaEE packages have been renamed, can this be updated for those class names?

When loading with 
```
java.lang.NoClassDefFoundError: javax/servlet/jsp/tagext/TagLibraryValidator
```

**Comment by sargue** [comment]
I guess it would need a new major version of the package or an entirely new artifact.

I don't need this change for any project so anyone willing to create a PR is very welcome. Otherwise this will need to wait until I got some free time.

**Comment by sargue** [comment]
Done. Thanks @jpschewe .
