### ISSUE TITLE
Clarify "styles" values

### ISSUE THREAD

**Issue by gmazza** [sargue/java-time-jsptags#3]
Text after most of the tags: 

style:	The style to use for formatting (see java.time format documentation for recognized style strings)
pattern:  The pattern to use for formatting (see java.time format documentation for recognized pattern strings)

It would be good near the top of the docs if you hyperlinked to where the styles and patterns are defined.  Patterns are easy:  https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html, but I'm not sure what you're referring to as "style" -- closest I can see is this: https://docs.oracle.com/javase/8/docs/api/java/time/format/package-summary.html, but the "MS" sample value given in LocalDateTime doesn't fit as an acceptable value for style for any of those *Styles (FormatStyle, ResolverStyle, etc.) given.

**Comment by gmazza** [comment]
Oh I see now that the style definitions are defined here:  http://joda-time.sourceforge.net/contrib/jsptags/userguide.html, probably good to clarify still though.

**Comment by sargue** [comment]
Sorry about that. You guess correctly. Updating documentation to better explain that.

Indeed the expected value are two characters, each an style from https://docs.oracle.com/javase/8/docs/api/java/time/format/FormatStyle.html

It's quite the same behaviour as the original Joda tags.

Thanks for reporting.
