### ISSUE TITLE
https://sargue.net/jsptags/time/ produces a 404

### ISSUE THREAD

**Issue by bphilipnyc** [sargue/java-time-jsptags#6]
Produces:

>  org.apache.jasper.JasperException: The absolute uri: http://sargue.net/jsptags/time cannot be resolved in either web.xml or the jar files deployed with this application
> 	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:55)

**Comment by sargue** [comment]
Yes, I haven't deployed any file on the taglib URI. Should I?

I have the understanding that the taglib URI is just a namespace, like the name of a Java package for example. What is expected to be found there? Could you please share a working public URI for another taglib as a reference?

**Comment by sargue** [comment]
Closing on inactivity.
