### ISSUE TITLE
Make Util.createFormatterForStyle public

### ISSUE THREAD

**Issue by daiscog** [sargue/java-time-jsptags#7]
Hello!

It would be useful (at least for me) if the Util.createFormatterForStyle method was public; any chance of modifying it so?

My use case:  I'm preparing some JSON in a servlet for an AJAX within which I want to add a displayValue field.

Many thanks,

David

**Comment by sargue** [comment]
I'm far from an expert on public APIs but I don't see why not.

Expect a new version in the following days (based on my amount of spare time).
