### ISSUE TITLE
java.time.format.DateTimeParseException: Text '2018-02-06' could not be parsed at index 4

### ISSUE THREAD

**Issue by digz6666** [sargue/java-time-jsptags#8]
I used parseLocalDate but it throws following exception:
```
java.time.format.DateTimeParseException: Text '2018-02-06' could not be parsed at index 4
```

The code (theDate is LocalDate):
```
<javatime:parseLocalDate value="${theDate}" pattern="yyyy/MM/dd"/>
```

**Comment by sargue** [comment]
You say that `theDate` is an instance of `LocalDate`. Are you sure you want to parse it (`<javatime:parseLocalDate>`) or are your instead trying to print it formatted ('<javatime:format>') ?

Because parsing it doesn't make sense to me.

**Comment by digz6666** [comment]
@sargue Ah my bad, I should have used javatime:format method :)
